/*++
Module Name:
    device.c - Device handling events for example driver.

Abstract:
    This is a C version of a very simple sample driver that illustrates
    how to use the driver framework and demonstrates best practices.
--*/

#include "driver.h"
#include "trace.h"
#include "device.tmh"

#ifdef ALLOC_PRAGMA
#pragma alloc_text (PAGE, ECTestDeviceCreate)
#endif


NTSTATUS
ECTestDeviceCreate(
    PWDFDEVICE_INIT DeviceInit
    )
/*++

Routine Description:

    Worker routine called to create a device and its software resources.

Arguments:

    DeviceInit - Pointer to an opaque init structure. Memory for this
                    structure will be freed by the framework when the WdfDeviceCreate
                    succeeds. So don't access the structure after that point.

Return Value:

    NTSTATUS

--*/
{
    WDF_OBJECT_ATTRIBUTES   deviceAttributes;
    PDEVICE_CONTEXT deviceContext;
    WDFDEVICE device;
    NTSTATUS status;

    PAGED_CODE();

    WDF_OBJECT_ATTRIBUTES_INIT_CONTEXT_TYPE(&deviceAttributes, DEVICE_CONTEXT);
    status = WdfDeviceCreate(&DeviceInit, &deviceAttributes, &device);

    if (NT_SUCCESS(status)) {
        //
        // Get the device context and initialize it. DeviceContextGet is an
        // inline function generated by WDF_DECLARE_CONTEXT_TYPE macro in the
        // device.h header file. This function will do the type checking and return
        // the device context. If you pass a wrong object  handle
        // it will return NULL and assert if run under framework verifier mode.
        //
        deviceContext = DeviceContextGet(device);
        deviceContext->PendingRequest = NULL;

#if defined(EC_TEST_NOTIFICATIONS) && defined(ENABLE_NOTIFICATION_SIMULATION)
        deviceContext->Timer = NULL;
#endif

#ifdef EC_TEST_NOTIFICATIONS
        WDF_OBJECT_ATTRIBUTES attributes;

        WDF_OBJECT_ATTRIBUTES_INIT(&attributes);
        attributes.ParentObject = device;
        status = WdfWaitLockCreate(&attributes, &deviceContext->NotificationLock);

        if (NT_SUCCESS(status)) {
#endif // EC_TEST_NOTIFICATIONS

            //
            // Create a device interface so that application can find and talk
            // to us.
            //
            status = WdfDeviceCreateDeviceInterface(
                device,
                &GUID_DEVINTERFACE_ECTEST,
                NULL // ReferenceString
                );

            if (NT_SUCCESS(status)) {
                //
                // Initialize the I/O Package and any Queues
                //
                status = ECTestQueueInitialize(device);

#if defined(EC_TEST_NOTIFICATIONS) && defined(ENABLE_NOTIFICATION_SIMULATION)
                WDF_OBJECT_ATTRIBUTES timerAttributes;
                WDF_TIMER_CONFIG timerConfig;
                // Initialize the timer configuration
                WDF_TIMER_CONFIG_INIT_PERIODIC(&timerConfig, TimerCallback, 1000); // 1000 ms period

                // Set the timer attributes
                WDF_OBJECT_ATTRIBUTES_INIT(&timerAttributes);
                timerAttributes.ParentObject = device;

                // Create the timer
                if (!NT_SUCCESS(WdfTimerCreate(&timerConfig, &timerAttributes, &deviceContext->Timer))) {

                    // Ignore the failure, and allow the device to create successfully
                    Trace(TRACE_LEVEL_ERROR, TRACE_DEVICE,"WdfTimerCreate failed\n");
                    deviceContext->Timer = NULL;
                }
#endif
            }
#ifdef EC_TEST_NOTIFICATIONS
        }
#endif // EC_TEST_NOTIFICATIONS
    }

    return status;
}
